org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2G
mod_version=1.1.0
maven_group=com.stool.tpsoverlay
archives_base_name=tps-overlay
minecraft_version=26.2
loom_version=1.17.+
loader_version=0.19.5
fabric_version=0.19.5+26.2
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-26.0.0.35-hotspot
